"""create meeting blockers table

Revision ID: 09c26e231c92
Revises: bec801eb536d
Create Date: 2026-09-22 12:46:29.692020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c26e231c92'
down_revision: Union[str, Sequence[str], None] = 'bec801eb536d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_blockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blocker', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('meeting_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_note_id'], ['meeting_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_blockers_id'), 'meeting_blockers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_blockers_id'), table_name='meeting_blockers')
    op.drop_table('meeting_blockers')
    # ### end Alembic commands ###
