"""create meeting decisions table

Revision ID: 2b50ed67426a
Revises: 038086d1f678
Create Date: 2026-09-21 16:10:37.577679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b50ed67426a'
down_revision: Union[str, Sequence[str], None] = '038086d1f678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('meeting_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_note_id'], ['meeting_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_decisions_id'), 'meeting_decisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_decisions_id'), table_name='meeting_decisions')
    op.drop_table('meeting_decisions')
    # ### end Alembic commands ###
