"""add github sync enabled to projects

Revision ID: 51368b70fdf4
Revises: 903d115798ec
Create Date: 2026-07-14 14:50:56.759866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51368b70fdf4'
down_revision: Union[str, Sequence[str], None] = '903d115798ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "projects",
        sa.Column(
            "github_sync_enabled",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_sync_enabled')
    # ### end Alembic commands ###
