"""extend github repository model

Revision ID: 90f39182349c
Revises: 51368b70fdf4
Create Date: 2026-07-17 15:23:49.257707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f39182349c'
down_revision: Union[str, Sequence[str], None] = '51368b70fdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('github_repositories', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('github_repositories', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('github_repositories', sa.Column('default_branch', sa.String(), nullable=True))
    op.add_column('github_repositories', sa.Column('language', sa.String(), nullable=True))
    op.add_column('github_repositories', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('github_repositories', sa.Column('forks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('github_repositories', 'forks')
    op.drop_column('github_repositories', 'stars')
    op.drop_column('github_repositories', 'language')
    op.drop_column('github_repositories', 'default_branch')
    op.drop_column('github_repositories', 'private')
    op.drop_column('github_repositories', 'full_name')
    # ### end Alembic commands ###
