"""create sprints table

Revision ID: b0625f39a4b1
Revises: d4f8991bd46d
Create Date: 2026-07-23 15:04:13.744638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0625f39a4b1'
down_revision: Union[str, Sequence[str], None] = 'd4f8991bd46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprints', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('sprints', 'start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('sprints', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('sprints', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sprints', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sprints', 'end_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sprints', 'start_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('sprints', 'created_at')
    # ### end Alembic commands ###
